---
openapi: 3.0.0
info:
  title: MrSpecter Lobby API
  description: Lobby API
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/anserjan/Lobby/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /lobbies:
    post:
      summary: Creates lobby
      responses:
        "201":
          description: lobby created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        "400":
          description: invalid user
        "500":
          description: server error
  /lobbies/{lobbyId}:
    get:
      summary: Get specific lobby, register in lobbylist
      parameters:
      - name: lobbyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "201":
          description: lobby found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        "401":
          description: unauthorized
        "404":
          description: lobby not found
    put:
      summary: Update lobby
      parameters:
      - name: lobbyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        description: data to update gamemode
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lobby'
        required: true
      responses:
        "200":
          description: lobby successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        "401":
          description: unauthorized
        "404":
          description: lobby not found
    delete:
      summary: Delete lobby
      parameters:
      - name: lobbyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: lobby deleted
        "401":
          description: unauthorized
        "404":
          description: lobby not found
  /lobbies/{lobbyId}/leave:
    get:
      summary: Remove user from lobby list
      parameters:
      - name: lobbyId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: lobby successfully left
        "401":
          description: unauthorized
        "404":
          description: lobby not found
components:
  schemas:
    Lobby:
      type: object
      properties:
        _id:
          type: string
        gamemode:
          type: string
        magick_link:
          type: string
        users:
          type: array
          items:
            type: string
    User:
      type: object
      properties:
        _id:
          type: string
        userID:
          type: string
        userName:
          type: string
        isAdministrator:
          type: boolean
    Gamemode:
      type: object
      properties:
        _id:
          type: string
        huntedUser:
          type: string
        updatedAt:
          type: string
        maximumUsers:
          type: integer
        gameBorders:
          type: array
          items:
            type: string
        gametime:
          type: integer
